#!/bin/sh

### BEGIN INIT INFO
# Provides:          djangoaws
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: combined starting and stop of a single djangoaws web node
### END INIT INFO

PROJECT_DIR=/home/ubuntu/djangoaws_project

start() {
    echo "starting"
    $PROJECT_DIR/venv/bin/python $PROJECT_DIR/djangoaws/manage.py migrate
    $PROJECT_DIR/venv/bin/python $PROJECT_DIR/djangoaws/manage.py collectstatic --noinput
    sudo systemctl restart gunicorn
    sudo systemctl restart nginx
}

stop () {
    echo "stopping"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
esac
